class BullockCart{
	public static void main(String[] args){
		 int cartId=123;
		 String cartName="Bandi";
		 byte numberOfBulls=2;
		 byte numberOfWheels=2;
		 double cartWeight=255.56;
		 double loadCapacity=550.33;
		 String ownerFisrtName="Chiranth";
		 String ownerLastName="Vishwakarma";
		 int ownerAge=22;
		 int distance=25;
		 double avgSpeed=12.5;
		 int journeyTime=9;
		 double cartPrice=650;
		 boolean isLoaded=true;
		 boolean isMoving=true;
		 double ropeLength=3.5;
		 String woodType="Teak";
		 double bullStrenght=0.5;
		 double loadWeight=355.33;
		 int routeNumber=11;
		 double maintananceCost=300;
		 
		 System.out.println("BullockCart Details:");
		 System.out.println("Cart ID:"+cartId);
		 System.out.println("Cart Name:"+cartName);
		 System.out.println("Number of Bulls:"+numberOfBulls+" Bulls");
		 System.out.println("Weightt of the Cart:"+cartWeight+"KG");
		 System.out.println("Load Capacity:"+loadCapacity+"KG");
		 System.out.println("Owner First name:"+ownerFisrtName);
		 System.out.println("Owner Last name:"+ownerLastName);
		 System.out.println("Owner Age:"+ownerAge+" years");
		 System.out.println("Total Distance going to cover:"+distance+" KM");
		 System.out.println("Avg speed of the Cart:"+avgSpeed+" kmph");
		 System.out.println("Totals Journey in hours:"+journeyTime+"hours");
		 System.out.println("Price of the Cart :₹"+cartPrice);
		 System.out.println("Is cart loded:"+isLoaded);
		 System.out.println("Is cart is loving:"+isMoving);
	     System.out.println("Lenght of the Rope:"+ropeLength+" M");
		 System.out.println("Weight of the load:"+loadWeight+" KG");
		 System.out.println("Type of wood id used to make the cart:"+woodType);
		 System.out.println("Strenght of the bull:"+bullStrenght+" HP");
		 System.out.println("Number of the route:"+routeNumber);
		 System.out.println("Maintainance Cost :₹"+maintananceCost);
		 System.out.println();
		 
		 cartId=124;
		 cartName="Bandi1";
		 numberOfBulls=4;
		 numberOfWheels=2;
		 cartWeight=25.56;
		 loadCapacity=55.33;
		 ownerFisrtName="Chiranthh";
		 ownerLastName="Vishwakarmaa";
		 ownerAge=23;
		 distance=28;
		 avgSpeed=16.5;
		 journeyTime=12;
		 cartPrice=450;
		 isLoaded=false;
		 isMoving=false;
		 ropeLength=4.5;
		 woodType="RoseWood";
		 bullStrenght=0.8;
		 loadWeight=356.33;
		 routeNumber=16;
		 maintananceCost=350;
		 
		 System.out.println("BullockCart Details:");
		 System.out.println("Cart ID:"+cartId);
		 System.out.println("Cart Name:"+cartName);
		 System.out.println("Number of Bulls:"+numberOfBulls+" Bulls");
		 System.out.println("Weightt of the Cart:"+cartWeight+"KG");
		 System.out.println("Load Capacity:"+loadCapacity+"KG");
		 System.out.println("Owner First name:"+ownerFisrtName);
		 System.out.println("Owner Last name:"+ownerLastName);
		 System.out.println("Owner Age:"+ownerAge+" years");
		 System.out.println("Total Distance going to cover:"+distance+" KM");
		 System.out.println("Avg speed of the Cart:"+avgSpeed+" kmph");
		 System.out.println("Totals Journey in hours:"+journeyTime+"hours");
		 System.out.println("Price of the Cart :₹"+cartPrice);
		 System.out.println("Is cart loded:"+isLoaded);
		 System.out.println("Is cart is loving:"+isMoving);
	     System.out.println("Lenght of the Rope:"+ropeLength+" M");
		 System.out.println("Weight of the load:"+loadWeight+" KG");
		 System.out.println("Type of wood id used to make the cart:"+woodType);
		 System.out.println("Strenght of the bull:"+bullStrenght+" HP");
		 System.out.println("Number of the route:"+routeNumber);
		 System.out.println("Maintainance Cost :₹"+maintananceCost);
	}
}
