class Energy {
	public static void main(String[] args) {
		int energyId = 101;
		int voltage = 230;
		int current = 10;
		int power = 2300;
		int frequency = 50;
		int efficiency = 90;
		double energyConsumed = 12.5;
		double unitCost = 8.50;
		int batteryCapacity = 5000;
		int chargingTime = 120;
		int backupTime = 8;
		int temperature = 30;
		double solarOutput = 3.5;
		double windSpeed = 15.5;
		char energySource = 'S';
		char powerMode = 'A';
		char connectionType = 'G';
		double carbonEmission = 2.4;
		boolean isRenewable = true;
		boolean isPowerAvailable = true;

		System.out.println("Energy Information");
		System.out.println("Energy ID:" + energyId);
		System.out.println("Voltage:" + voltage);
		System.out.println("Current:" + current);
		System.out.println("Power:" + power);
		System.out.println("Frequency:" + frequency);
		System.out.println("Efficiency:" + efficiency);
		System.out.println("Energy Consumed:" + energyConsumed);
		System.out.println("Unit Cost:" + unitCost);
		System.out.println("Battery Capacity:" + batteryCapacity);
		System.out.println("Charging Time:" + chargingTime);
		System.out.println("Backup Time:" + backupTime);
		System.out.println("Temperature:" + temperature);
		System.out.println("Solar Output:" + solarOutput);
		System.out.println("Wind Speed:" + windSpeed);
		System.out.println("Energy Source:" + energySource);
		System.out.println("Power Mode:" + powerMode);
		System.out.println("Connection Type:" + connectionType);
		System.out.println("Carbon Emission:" + carbonEmission);
		System.out.println("Is Renewable:" + isRenewable);
		System.out.println("Is Power Available:" + isPowerAvailable);
		System.out.println("");

		energyId = 102;
		voltage = 240;
		current = 12;
		power = 2880;
		frequency = 60;
		efficiency = 95;
		energyConsumed = 15.8;
		unitCost = 9.25;
		batteryCapacity = 6000;
		chargingTime = 100;
		backupTime = 10;
		temperature = 28;
		solarOutput = 4.2;
		windSpeed = 18.0;
		energySource = 'W';
		powerMode = 'M';
		connectionType = 'B';
		carbonEmission = 1.8;
		isRenewable = false;
		isPowerAvailable = false;

		System.out.println("Energy ID:" + energyId);
		System.out.println("Voltage:" + voltage);
		System.out.println("Current:" + current);
		System.out.println("Power:" + power);
		System.out.println("Frequency:" + frequency);
		System.out.println("Efficiency:" + efficiency);
		System.out.println("Energy Consumed:" + energyConsumed);
		System.out.println("Unit Cost:" + unitCost);
		System.out.println("Battery Capacity:" + batteryCapacity);
		System.out.println("Charging Time:" + chargingTime);
		System.out.println("Backup Time:" + backupTime);
		System.out.println("Temperature:" + temperature);
		System.out.println("Solar Output:" + solarOutput);
		System.out.println("Wind Speed:" + windSpeed);
		System.out.println("Energy Source:" + energySource);
		System.out.println("Power Mode:" + powerMode);
		System.out.println("Connection Type:" + connectionType);
		System.out.println("Carbon Emission:" + carbonEmission);
		System.out.println("Is Renewable:" + isRenewable);
		System.out.println("Is Power Available:" + isPowerAvailable);
	}
}