class Gun {
	public static void main(String[] args) {
		int gunId = 201;
		int bulletCapacity = 30;
		char gunType = 'R';
		double gunWeight = 3.8;
		int bulletsLoaded = 25;
		int bulletsRemaining = 25;
		String companyName = "Defence Arms Pvt Ltd";
		String ownerName = "Rakesh";
		int ownerAge = 38;
		String ownerCity = "Bengaluru";
		String deliveryTo = "Mysuru";
		String deliveryFrom = "Bengaluru";
		double distanceInKm = 145.75;
		double price = 85000.50;
		double barrelLength = 16.5;
		int modelNumber = 501;
		int warrantyYears = 5;
		int manufacturedYear = 2025;
		String feature = "Semi Automatic";
		int licenseExpiryYear = 2030;

		System.out.println("***** Gun Details *****");
		System.out.println("Gun ID:" + gunId);
		System.out.println("Bullet Capacity:" + bulletCapacity);
		System.out.println("Gun Type:" + gunType);
		System.out.println("Gun Weight:" + gunWeight);
		System.out.println("Bullets Loaded:" + bulletsLoaded);
		System.out.println("Bullets Remaining:" + bulletsRemaining);
		System.out.println("Company Name:" + companyName);
		System.out.println("Owner Name:" + ownerName);
		System.out.println("Owner Age:" + ownerAge);
		System.out.println("Owner City:" + ownerCity);
		System.out.println("Delivery To:" + deliveryTo);
		System.out.println("Delivery From:" + deliveryFrom);
		System.out.println("Distance in KM:" + distanceInKm + " KM");
		System.out.println("Gun Price:" + price);
		System.out.println("Barrel Length:" + barrelLength);
		System.out.println("Model Number:" + modelNumber);
		System.out.println("Warranty Years:" + warrantyYears);
		System.out.println("Manufactured Year:" + manufacturedYear);
		System.out.println("Feature:" + feature);
		System.out.println("License Expiry Year:" + licenseExpiryYear);
		System.out.println();

		gunId = 202;
		bulletCapacity = 20;
		gunType = 'P';
		gunWeight = 2.5;
		bulletsLoaded = 18;
		bulletsRemaining = 18;
		companyName = "Secure Weapons Ltd";
		ownerName = "Mahesh";
		ownerAge = 42;
		ownerCity = "Mangaluru";
		deliveryTo = "Hubballi";
		deliveryFrom = "Mangaluru";
		distanceInKm = 360.80;
		price = 65000.75;
		barrelLength = 12.0;
		modelNumber = 502;
		warrantyYears = 6;
		manufacturedYear = 2026;
		feature = "Fully Automatic";
		licenseExpiryYear = 2032;

		System.out.println("Gun ID:" + gunId);
		System.out.println("Bullet Capacity:" + bulletCapacity);
		System.out.println("Gun Type:" + gunType);
		System.out.println("Gun Weight:" + gunWeight);
		System.out.println("Bullets Loaded:" + bulletsLoaded);
		System.out.println("Bullets Remaining:" + bulletsRemaining);
		System.out.println("Company Name:" + companyName);
		System.out.println("Owner Name:" + ownerName);
		System.out.println("Owner Age:" + ownerAge);
		System.out.println("Owner City:" + ownerCity);
		System.out.println("Delivery To:" + deliveryTo);
		System.out.println("Delivery From:" + deliveryFrom);
		System.out.println("Distance in KM:" + distanceInKm + " KM");
		System.out.println("Gun Price:" + price);
		System.out.println("Barrel Length:" + barrelLength);
		System.out.println("Model Number:" + modelNumber);
		System.out.println("Warranty Years:" + warrantyYears);
		System.out.println("Manufactured Year:" + manufacturedYear);
		System.out.println("Feature:" + feature);
		System.out.println("License Expiry Year:" + licenseExpiryYear);
	}
}