class Internship {
	public static void main(String[] args) {
		int internshipId = 301;
		int durationInMonths = 6;
		char internshipMode = 'O';
		double stipend = 15000.00;
		int workingHoursPerDay = 8;
		int totalProjects = 3;
		String companyName = "Xworkz";
		String mentorName = "Amit";
		int mentorAge = 35;
		String companyCity = "Bengaluru";
		String internshipLocation = "Rajajinagar";
		String collegeName = "MVJ College of Engineering";
		double distanceInKm = 18.50;
		double rating = 4.5;
		double attendancePercentage = 95.50;
		int employeeId = 1201;
		int joiningYear = 2026;
		int completionYear = 2027;
		String domain = "Java Development";
		int certificateId = 501;

		System.out.println("***** Internship Details *****");
		System.out.println("Internship ID:" + internshipId);
		System.out.println("Duration (Months):" + durationInMonths);
		System.out.println("Internship Mode:" + internshipMode);
		System.out.println("Stipend:" + stipend);
		System.out.println("Working Hours Per Day:" + workingHoursPerDay);
		System.out.println("Total Projects:" + totalProjects);
		System.out.println("Company Name:" + companyName);
		System.out.println("Mentor Name:" + mentorName);
		System.out.println("Mentor Age:" + mentorAge);
		System.out.println("Company City:" + companyCity);
		System.out.println("Internship Location:" + internshipLocation);
		System.out.println("College Name:" + collegeName);
		System.out.println("Distance:" + distanceInKm + " KM");
		System.out.println("Rating:" + rating);
		System.out.println("Attendance Percentage:" + attendancePercentage);
		System.out.println("Employee ID:" + employeeId);
		System.out.println("Joining Year:" + joiningYear);
		System.out.println("Completion Year:" + completionYear);
		System.out.println("Domain:" + domain);
		System.out.println("Certificate ID:" + certificateId);
		System.out.println();

		internshipId = 302;
		durationInMonths = 12;
		internshipMode = 'H';
		stipend = 25000.00;
		workingHoursPerDay = 9;
		totalProjects = 5;
		companyName = "Xworkz";
		mentorName = "Amit";
		mentorAge = 36;
		companyCity = "Bengaluru";
		internshipLocation = "Rajajinagar";
		collegeName = "MVJ College of Engineering";
		distanceInKm = 20.75;
		rating = 4.8;
		attendancePercentage = 98.00;
		employeeId = 1202;
		joiningYear = 2027;
		completionYear = 2028;
		domain = "Advanced Java";
		certificateId = 502;

		System.out.println("Internship ID:" + internshipId);
		System.out.println("Duration (Months):" + durationInMonths);
		System.out.println("Internship Mode:" + internshipMode);
		System.out.println("Stipend:" + stipend);
		System.out.println("Working Hours Per Day:" + workingHoursPerDay);
		System.out.println("Total Projects:" + totalProjects);
		System.out.println("Company Name:" + companyName);
		System.out.println("Mentor Name:" + mentorName);
		System.out.println("Mentor Age:" + mentorAge);
		System.out.println("Company City:" + companyCity);
		System.out.println("Internship Location:" + internshipLocation);
		System.out.println("College Name:" + collegeName);
		System.out.println("Distance:" + distanceInKm + " KM");
		System.out.println("Rating:" + rating);
		System.out.println("Attendance Percentage:" + attendancePercentage);
		System.out.println("Employee ID:" + employeeId);
		System.out.println("Joining Year:" + joiningYear);
		System.out.println("Completion Year:" + completionYear);
		System.out.println("Domain:" + domain);
		System.out.println("Certificate ID:" + certificateId);
	}
}